"""add to model User email and avatar

Revision ID: 902f97e8013c
Revises: dffa99a4a131
Create Date: 2025-03-19 20:48:13.192141

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "902f97e8013c"
down_revision: Union[str, None] = "dffa99a4a131"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("avatar", sa.String(length=255), nullable=True))
    op.add_column("users", sa.Column("confirmed", sa.Boolean(), nullable=True))
    op.execute("UPDATE users SET confirmed = TRUE WHERE confirmed IS NULL")
    op.alter_column("users", "confirmed", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "confirmed")
    op.drop_column("users", "avatar")
    # ### end Alembic commands ###
